/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publications/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publications/{publication_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPublicationAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publications/{publication_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSpecialistDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publications/{publication_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicationHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSources"];
        put?: never;
        post: operations["createSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSource"];
        trace?: never;
    };
    "/api/sources/{source_id}/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["collectSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importDemoSeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["collectEnabledSources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regulatory-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRegulatoryCases"];
        put?: never;
        post: operations["createRegulatoryCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regulatory-cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRegulatoryCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regulatory-cases/{case_id}/publications/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["linkPublicationToCase"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regulatory-cases/{case_id}/lifecycle-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLifecycleEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        SourceType: "rss" | "regulator" | "telegram" | "telegram_archive" | "file" | "seed";
        /** @enum {string} */
        Category: "regulation" | "reputation" | "competitor" | "trend" | "unknown";
        /** @enum {string} */
        Priority: "critical" | "high" | "medium" | "low" | "unknown";
        /** @enum {string} */
        LifecycleStage: "draft" | "introduced" | "adopted" | "published" | "effective" | "amended" | "repealed";
        SourceCreate: {
            name: string;
            type: components["schemas"]["SourceType"];
            /** Format: uri */
            url: string;
            /** @description Defaults to true when omitted */
            enabled?: boolean;
        };
        SourcePatch: {
            name?: string;
            /** Format: uri */
            url?: string;
            enabled?: boolean;
        };
        Source: {
            id: string;
            name: string;
            type: components["schemas"]["SourceType"];
            /** Format: uri */
            url: string;
            enabled: boolean;
            /** Format: date-time */
            last_checked_at: string | null;
            /** Format: date-time */
            last_success_at: string | null;
            last_error: string | null;
            is_demo: boolean;
        };
        Entity: {
            type: string;
            value: string;
        };
        Evidence: {
            claim: string;
            quote: string;
        };
        Criteria: {
            K1: number;
            K2: number;
            K3: number;
            K4: number;
            K5: number;
            K6: number;
            H1: boolean;
            H2: boolean;
            H3: boolean;
            H4: boolean;
        };
        Publication: {
            id: string;
            source_id: string;
            external_id: string;
            title: string;
            /** Format: uri */
            original_url: string;
            /** Format: date-time */
            published_at: string;
            /** Format: date-time */
            collected_at: string;
            content: string;
            content_hash: string;
            is_demo: boolean;
            latest_analysis_id: string | null;
        };
        AnalysisVersion: {
            id: string;
            publication_id: string;
            version: number;
            /** @enum {string} */
            analyzer: "replay" | "live_llm";
            model: string;
            prompt_version: string;
            input_hash: string;
            summary: string;
            facts: string[];
            entities: components["schemas"]["Entity"][];
            category: components["schemas"]["Category"];
            proposed_priority: components["schemas"]["Priority"];
            criteria: components["schemas"]["Criteria"];
            score: number;
            evidence: components["schemas"]["Evidence"][];
            uncertainty: number;
            needs_review: boolean;
            /** Format: date-time */
            created_at: string;
        };
        PublicationDetail: {
            publication: components["schemas"]["Publication"];
            latest_analysis: components["schemas"]["AnalysisVersion"] | null;
            latest_decision: components["schemas"]["SpecialistDecision"] | null;
        };
        PublicationList: {
            items: components["schemas"]["PublicationDetail"][];
            total: number;
            limit: number;
            offset: number;
        };
        AnalysisCreate: {
            /**
             * @description Defaults to replay when omitted
             * @enum {string}
             */
            analyzer?: "replay" | "live_llm";
        };
        /** @enum {string} */
        DecisionStatus: "confirmed" | "corrected" | "rejected";
        SpecialistDecisionCreate: {
            analysis_id: string;
            status: components["schemas"]["DecisionStatus"];
            final_summary?: string | null;
            final_category: components["schemas"]["Category"];
            final_priority: components["schemas"]["Priority"];
            comment?: string | null;
            author_id: string;
        };
        SpecialistDecision: {
            id: string;
            publication_id: string;
            analysis_id: string;
            version: number;
            status: components["schemas"]["DecisionStatus"];
            final_summary: string | null;
            final_category: components["schemas"]["Category"];
            final_priority: components["schemas"]["Priority"];
            comment: string | null;
            author_id: string;
            /** Format: date-time */
            created_at: string;
        };
        PublicationHistory: {
            publication_id: string;
            analyses: components["schemas"]["AnalysisVersion"][];
            decisions: components["schemas"]["SpecialistDecision"][];
        };
        RegulatoryCaseCreate: {
            title: string;
            registration_number: string;
            current_stage: components["schemas"]["LifecycleStage"];
            responsible_user_id: string;
            /** @description Defaults to an empty list when omitted */
            related_publication_ids?: string[];
        };
        RegulatoryCase: {
            id: string;
            title: string;
            registration_number: string;
            current_stage: components["schemas"]["LifecycleStage"];
            responsible_user_id: string;
            related_publication_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LifecycleEventCreate: {
            stage: components["schemas"]["LifecycleStage"];
            /** Format: date-time */
            occurred_at: string;
            /** Format: uri */
            confirmation_url: string;
            /** @enum {string} */
            confirmation_source_type: "regulator" | "official_publication";
            comment?: string | null;
            author_id: string;
        };
        LifecycleEvent: {
            id: string;
            regulatory_case_id: string;
            stage: components["schemas"]["LifecycleStage"];
            /** Format: date-time */
            occurred_at: string;
            /** Format: uri */
            confirmation_url: string;
            /** @enum {string} */
            confirmation_source_type: "regulator" | "official_publication";
            comment: string | null;
            author_id: string;
            /** Format: date-time */
            created_at: string;
        };
        RegulatoryCaseDetail: {
            regulatory_case: components["schemas"]["RegulatoryCase"];
            timeline: components["schemas"]["LifecycleEvent"][];
        };
        DemoSeedImportReport: {
            sources: number;
            publications: number;
            analyses: number;
            duplicates: number;
        };
        SourceCollectionResult: {
            source_id: string;
            /** @enum {string} */
            status: "success" | "partial" | "failed";
            collected: number;
            created: number;
            exact_duplicates: number;
            semantic_candidates: number;
            error: string | null;
        };
        CollectionReport: {
            /** @enum {string} */
            status: "completed" | "partial_failure" | "failed";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string;
            sources: components["schemas"]["SourceCollectionResult"][];
            collected: number;
            created: number;
            exact_duplicates: number;
            semantic_candidates: number;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PublicationId: string;
        SourceId: string;
        CaseId: string;
        /** @description Full-text query over title, content, tags, and entities */
        SearchQuery: string;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listPublications: {
        parameters: {
            query?: {
                /** @description Full-text query over title, content, tags, and entities */
                q?: components["parameters"]["SearchQuery"];
                source_id?: string;
                source_type?: components["schemas"]["SourceType"];
                published_from?: string;
                published_to?: string;
                category?: components["schemas"]["Category"];
                proposed_priority?: components["schemas"]["Priority"];
                needs_review?: boolean;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered publication feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationList"];
                };
            };
        };
    };
    getPublication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publication card with latest analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPublicationAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalysisCreate"];
            };
        };
        responses: {
            /** @description New immutable analysis version */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisVersion"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    createSpecialistDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialistDecisionCreate"];
            };
        };
        responses: {
            /** @description New immutable specialist decision */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistDecision"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getPublicationHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable analysis and decision history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationHistory"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
        };
    };
    createSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Source created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    updateSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatch"];
            };
        };
        responses: {
            /** @description Source updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    collectSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed collection report for one source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionReport"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    importDemoSeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Idempotent offline import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSeedImportReport"];
                };
            };
        };
    };
    collectEnabledSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed collection report for enabled sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionReport"];
                };
            };
        };
    };
    listRegulatoryCases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regulatory cases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulatoryCase"][];
                };
            };
        };
    };
    createRegulatoryCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegulatoryCaseCreate"];
            };
        };
        responses: {
            /** @description Regulatory case created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulatoryCase"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getRegulatoryCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case and append-only timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulatoryCaseDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    linkPublicationToCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: components["parameters"]["CaseId"];
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publication linked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createLifecycleEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifecycleEventCreate"];
            };
        };
        responses: {
            /** @description Lifecycle event appended */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleEvent"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Invalid lifecycle transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
}
